import './globals.css'
import { Inter } from 'next/font/google'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + " w-full"}>
        <header className='flex items-center gap-2 bg-purple-500'>
          <h1>Hei, Ola Normann!</h1>
          <Image
            src="/images/menu-hamburger-nav.svg"
            alt="Meny knapp"
            className="dark:invert ml-auto"
            width={30}
            height={30}
            priority
          />
        </header>
        <nav className="p-2 w-full items-center px-4 hidden">
          <Image
            src="/images/web-logo.png"
            alt="Arne Næss Logo"
            className="dark:invert"
            width={140}
            height={40}
            priority
          />

          <ul className="flex gap-3 ml-auto hidden lg:block">
            <li>Hjem</li>
            <li>Utforst</li>
            <li>Quiz</li>
            <li>Arkiv</li>
          </ul>
        </nav>
        <div>
          {children}
        </div>  
      </body>
    </html>
  )
}
