'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import { useState } from 'react'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [menuVisible, setMenuVisibility] = useState(false);

  return (
    <html lang="en">
      <body className={inter.className + " w-full"}>
        <header className='flex gap-2 h-28 p-2 pt-3 items-start px-4'>
        
          <div className="flex items-center w-full">
            <a
            href="/"
            rel="noopener noreferrer">
              <Image
                src="/images/web-logo.png"
                alt="Arne Næss Logo"
                className="dark:invert"
                width={140}
                height={40}
                priority
              />
          </a>

            <Image
              src="/images/menu-hamburger-nav.svg"
              alt="Meny knapp"
              className="dark:invert ml-auto"
              width={30}
              onClick={() => setMenuVisibility(!menuVisible)}
              height={30}
              priority
            />
          </div>
        </header>
        <nav className="p-2 w-full items-center px-4 hidden">
          <Image
            src="/images/web-logo.png"
            alt="Arne Næss Logo"
            className="dark:invert"
            width={140}
            height={40}
            priority
          />

          <ul className="flex gap-3 ml-auto hidden lg:block">
            <li>Hjem</li>
            <li>Utforst</li>
            <li>Quiz</li>
            <li>Arkiv</li>
          </ul>
        </nav>

        {children}
      </body>
    </html>
  )
}
